### ISSUE TITLE
Configuration Management - Hardcoded Values

### ISSUE THREAD

**Issue by AccursedGalaxy** [AccursedGalaxy/SentinelBot#31]
Many configuration values are hardcoded throughout the codebase instead of being managed through a proper configuration system.

### Current Issues
1. Hardcoded channel IDs in main.py
2. Hardcoded alert thresholds in alerts.py
3. Hardcoded timeframes and lookback periods
4. Discord role IDs in the code

### Proposed Solution
1. Create a proper configuration management system
2. Move all configuration to YAML/ENV files
3. Implement configuration validation
4. Add configuration documentation

Example configuration structure:
```yaml
discord:
  channels:
    money_flow: 1186336783261249638
    alerts:
      main: 1217104257216679987
      rvol: 1217105162351673455
      macd: 1217105204856488018
      vwap: 1217483711893733478

analysis:
  timeframe: 4h
  lookback_days: 31
  thresholds:
    rvol:
      up: 1.5
      extreme: 2.4
      down: 0.3
    vwap:
      above: 1.01
      below: 0.99
    large_order: 100000
```
